/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical_prescription_system;

import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
        

/**
 *
 * @author PLAMEN
 */
public class Medical_prescription extends javax.swing.JFrame {
    
    private JFrame frame;
  

    /**
     * Creates new form Medical_subscriptions
     */
    public Medical_prescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPrescription = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbUpdate = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbDoctor = new javax.swing.JButton();
        jbAppointment = new javax.swing.JButton();
        jbPatient = new javax.swing.JButton();
        jbReset = new javax.swing.JButton();
        jbPerscription = new javax.swing.JButton();
        jbLogin = new javax.swing.JButton();
        jbPrint = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jReference = new javax.swing.JLabel();
        jbNameTablets = new javax.swing.JLabel();
        jNumTab = new javax.swing.JLabel();
        jDose = new javax.swing.JLabel();
        jIssueData = new javax.swing.JLabel();
        jLOT = new javax.swing.JLabel();
        jDayDose = new javax.swing.JLabel();
        jExDate = new javax.swing.JLabel();
        jSideEffects = new javax.swing.JLabel();
        jStorageAdvice = new javax.swing.JLabel();
        jFurthInfor = new javax.swing.JLabel();
        jUse = new javax.swing.JLabel();
        jDriving = new javax.swing.JLabel();
        jNHSnum = new javax.swing.JLabel();
        jPatientID = new javax.swing.JLabel();
        jDOB = new javax.swing.JLabel();
        jPatientName = new javax.swing.JLabel();
        jAddress = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jtxtDose = new javax.swing.JTextField();
        jtxtReference = new javax.swing.JTextField();
        jtxtLOT = new javax.swing.JTextField();
        jtxtNumberTablets = new javax.swing.JTextField();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jtxtSideEffects = new javax.swing.JTextField();
        jtxtDriving = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtHowToUse = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jtxtDateOfBirth = new javax.swing.JTextField();
        jtxtPatientAddress = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane4.setViewportView(jtxtPrescription);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(432, 432, 432)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 540, 470));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medical Prescription System");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1400, -1));

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPrescription.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPrescription.setText("Patient Prescription");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(jPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPrescription)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 870, 70));

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jbUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbUpdate.setText("Update");
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        jbDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbDelete.setText("Delete");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });

        jbDoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbDoctor.setText("Doctor");
        jbDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDoctorActionPerformed(evt);
            }
        });

        jbAppointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbAppointment.setText("GP Appointment");
        jbAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAppointmentActionPerformed(evt);
            }
        });

        jbPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbPatient.setText("Patient");
        jbPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPatientActionPerformed(evt);
            }
        });

        jbReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbReset.setText("Reset");
        jbReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResetActionPerformed(evt);
            }
        });

        jbPerscription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbPerscription.setText("Perscription");
        jbPerscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPerscriptionActionPerformed(evt);
            }
        });

        jbLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbLogin.setText("Login");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });

        jbPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbPrint.setText("Print");
        jbPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrintActionPerformed(evt);
            }
        });

        jbExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbExit.setText("Exit");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbReset, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPerscription, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPerscription, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbReset, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 600, 1610, 60));

        jReference.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jReference.setText("Reference No.:");
        getContentPane().add(jReference, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jbNameTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbNameTablets.setText("Name of tablets:");
        getContentPane().add(jbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jNumTab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jNumTab.setText("Number of tablets:");
        getContentPane().add(jNumTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDose.setText("Dose (mg):");
        getContentPane().add(jDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jIssueData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jIssueData.setText("Issued Data:");
        getContentPane().add(jIssueData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLOT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLOT.setText("LOT:");
        getContentPane().add(jLOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jDayDose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDayDose.setText("Daily Dose:");
        getContentPane().add(jDayDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jExDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jExDate.setText("Exp Date:");
        getContentPane().add(jExDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jSideEffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSideEffects.setText("Possible side effects:");
        getContentPane().add(jSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jStorageAdvice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jStorageAdvice.setText("Storage Advice:");
        getContentPane().add(jStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jFurthInfor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFurthInfor.setText("Further Information:");
        getContentPane().add(jFurthInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jUse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUse.setText("How to use medication:");
        getContentPane().add(jUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jDriving.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDriving.setText("Driving: ");
        getContentPane().add(jDriving, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 220, -1));

        jNHSnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jNHSnum.setText("Doctor NHS No.:");
        getContentPane().add(jNHSnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        jPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPatientID.setText("Patient ID:");
        getContentPane().add(jPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jDOB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDOB.setText("Date of birth:");
        getContentPane().add(jDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        jPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPatientName.setText("Patient Name:");
        getContentPane().add(jPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        jAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jAddress.setText("Patient Address:");
        getContentPane().add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Make a selection:", "Ibuprofen", "Co-Codamol", "Paracetamol", "Amlodipine", "Nurofen", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 170, -1));
        getContentPane().add(jtxtReference, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 170, -1));

        jtxtLOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLOTActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtLOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 170, -1));
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 170, -1));
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 170, -1));

        jtxtIssuedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIssuedDateActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 170, -1));
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 170, -1));

        jtxtSideEffects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSideEffectsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 170, -1));
        getContentPane().add(jtxtDriving, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 170, -1));

        jtxtFurtherInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFurtherInformationActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 170, -1));
        getContentPane().add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 170, -1));
        getContentPane().add(jtxtHowToUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 170, -1));
        getContentPane().add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 170, -1));
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 170, -1));
        getContentPane().add(jtxtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 170, -1));
        getContentPane().add(jtxtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 170, -1));
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 170, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets:", "Reference No:", "Dose(mg)", "Number of tablets:", "LOT:", "Issued Date:", "Exp Date:", "Daily Dose:", "Possible Side Effects:", "Further Information:", "Storage Advice:", "Driving:", "How to use medication:", "Patient ID:", "Doctor NHS No:", "Patient Name:", "Date of birth:", "Patient Address"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1400, 480));

        jButton10.setText("Login");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox3.getSelectedItem().equals("Ibuprofen")){
            jtxtReference.setText("Ibuprofen");
            jtxtDose.setText("2");
            jtxtNumberTablets.setText("30");
            jtxtLOT.setText("551025875");
            jtxtIssuedDate.setText("05/01/2020");
            jtxtExpDate.setText("04/01/2021");
            jtxtDailyDose.setText("3");
            jtxtSideEffects.setText("Bleeding");
            
            jtxtFurtherInformation.setText("Place Dispencary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDriving.setText("Not recommended");
            jtxtHowToUse.setText("Use water");
            jtxtPatientID.setText("B007939");
            jtxtDoctorNHSNo.setText("PI126752");

            
        }else if(jComboBox3.getSelectedItem().equals("Co-Codamol")){
            jtxtReference.setText("Co-Codamol");
            jtxtDose.setText("3");
            jtxtNumberTablets.setText("44");
            jtxtLOT.setText("55178275");
            jtxtIssuedDate.setText("02/03/2020");
            jtxtExpDate.setText("02/03/2024");
            jtxtDailyDose.setText("4");
            jtxtSideEffects.setText("Headache,Constipation");
            
            jtxtFurtherInformation.setText("Keep away from childrens");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDriving.setText("Not recommended");
            jtxtHowToUse.setText("Use water");
            jtxtPatientID.setText("B0076639");
            jtxtDoctorNHSNo.setText("MSI1632523");
          
            
        }else if(jComboBox3.getSelectedItem().equals("Paracetamol")){
            jtxtReference.setText("Paracetamol");
            jtxtDose.setText("4");
            jtxtNumberTablets.setText("24");
            jtxtLOT.setText("51235875");
            jtxtIssuedDate.setText("01/01/2020");
            jtxtExpDate.setText("01/01/2023");
            jtxtDailyDose.setText("4");
            jtxtSideEffects.setText("Headache,vomiting");
            
            jtxtFurtherInformation.setText("Place Dispencary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDriving.setText("Not recommended");
            jtxtHowToUse.setText("Use water");
            jtxtPatientID.setText("B00793955");
            jtxtDoctorNHSNo.setText("MI126752");
       
            
        }else if(jComboBox3.getSelectedItem().equals("Amlodipine")){
            jtxtReference.setText("Amlodipine");
            jtxtDose.setText("4");
            jtxtNumberTablets.setText("28");
            jtxtLOT.setText("673225875");
            jtxtIssuedDate.setText("05/04/2020");
            jtxtExpDate.setText("05/04/2022");
            jtxtDailyDose.setText("2");
            jtxtSideEffects.setText("Bleeding,Feeling sleepy");
            
            jtxtFurtherInformation.setText("Place Dispencary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDriving.setText("Not recommended");
            jtxtHowToUse.setText("Use water");
            jtxtPatientID.setText("B004539");
            jtxtDoctorNHSNo.setText("PP452252");

        } else if(jComboBox3.getSelectedItem().equals("Nurofen")){
            jtxtReference.setText("Nurofen");
            jtxtDose.setText("4");
            jtxtNumberTablets.setText("20");
            jtxtLOT.setText("551025875");
            jtxtIssuedDate.setText("22/10/2019");
            jtxtExpDate.setText("22/10/2023");
            jtxtDailyDose.setText("3");
            jtxtSideEffects.setText("Dizziness,Headache");
            jtxtFurtherInformation.setText("Place Dispencary");
            jtxtStorageAdvice.setText("Less than 20%");
            jtxtDriving.setText("Not recommended");
            jtxtHowToUse.setText("Use water");
            jtxtPatientID.setText("B9862339");
            jtxtDoctorNHSNo.setText("MI126752");

        }else {
            jtxtReference.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLOT.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");
            jtxtSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDriving.setText("");
            jtxtHowToUse.setText("");
            jtxtPatientID.setText("");
            jtxtDoctorNHSNo.setText("");
            jtxtPatientName.setText("");
            jtxtDateOfBirth.setText("");
            jtxtPatientAddress.setText("");
            
        }
        
        
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jtxtIssuedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIssuedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIssuedDateActionPerformed

    private void jtxtSideEffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSideEffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSideEffectsActionPerformed

    private void jtxtFurtherInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFurtherInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFurtherInformationActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Medical Perscription System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        
        System.exit(0); 
      
        }
        
    }//GEN-LAST:event_jbExitActionPerformed

    private void jbAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAppointmentActionPerformed

    // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);


    }//GEN-LAST:event_jbAppointmentActionPerformed

    private void jbPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrintActionPerformed
            // TODO add your handling code here:
        
        try{
            jTextArea1.print();
        }catch (PrinterException pe){
            Logger.getLogger(Medical_prescription.class.getName()).log(Level.SEVERE, null, pe);
        }
        
    }//GEN-LAST:event_jbPrintActionPerformed

    private void jbPerscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPerscriptionActionPerformed
        
        String quantity1 = (jtxtReference.getText());
        String quantity2 = (jtxtDose.getText());
        String quantity3 = (jtxtNumberTablets.getText());
        String quantity4 = (jtxtLOT.getText());
        String quantity5= (jtxtDailyDose.getText());
        String quantity6 = (jtxtSideEffects.getText());
        String quantity7 = (jtxtFurtherInformation.getText());
        String quantity8 = (jtxtHowToUse.getText());
        String quantity9 = (jtxtPatientID.getText());
        String quantity10 = (jtxtPatientName.getText());
        String quantity11 = (jtxtDateOfBirth.getText());
        String quantity12 = (jtxtPatientAddress.getText());
        String quantity13 = ("");
        
        if(jComboBox3.getSelectedItem().equals("Ibuprofen")){
            quantity13 = "Ibuprofen";
        }else if(jComboBox3.getSelectedItem().equals("Co-Codamol")){
            quantity13 = "Co-Codamol";
        }else if(jComboBox3.getSelectedItem().equals("Paracetamol")){
            quantity13 = "Paracetamol";
        }else if(jComboBox3.getSelectedItem().equals("Amlodipin")){
            quantity13 = "Amlodipin";
        }else if(jComboBox3.getSelectedItem().equals("Nurofen")){
            quantity13 = "Nurofen";
        }
        
        
        jPrescription.setText("");
        jtxtPrescription.append("\t\n\t\tMedical Management System\n" 
        + "\nPatient Name:\t\t"    + quantity10 
        + "\nDate of Birth:\t\t"    + quantity11
        +"\nPatient Address: \t" +quantity12
        +"\nPrescription \t\t" + quantity13
        +"\nReference:\t\t" + quantity1
        +"\nDose:\t\t"    + quantity2
        +"\nNumber of tablets:\t"  + quantity3
        +"\nLOT:\t\t"    + quantity4
        +"\nDaily Dose:\t\t"    + quantity5
        +"\nPossible Side Effects:\t"    + quantity6
        +"\nFurther Information:\t"    + quantity7
        +"\nHow to use the medication:\t"    + quantity8
        +"\nPatient ID:\t\t"    + quantity9
        +"\n\nPatient Instructions: \tWE have introduced a free text confirmation\n\t\t"
                + "Text reminders for appointment.");
        
    }//GEN-LAST:event_jbPerscriptionActionPerformed

    private void jbPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPatientActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbPatientActionPerformed

    private void jtxtLOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLOTActionPerformed

    private void jbResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResetActionPerformed
        // TODO add your handling code here:
            jtxtReference.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLOT.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");
            jtxtSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDriving.setText("");
            jtxtHowToUse.setText("");
            jtxtPatientID.setText("");
            jtxtDoctorNHSNo.setText("");
            jtxtPatientName.setText("");
            jtxtDateOfBirth.setText("");
            jtxtPatientAddress.setText("");
            jComboBox3.getModel().setSelectedItem("Make a selection");
    }//GEN-LAST:event_jbResetActionPerformed

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        // TODO add your handling code here:
        
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        if(jTable3.getSelectedRow() == -1){
            if(jTable3.getRowCount() == 10){
                JOptionPane.showMessageDialog(null, "No data to delete","Medical Management System",
                        JOptionPane.OK_OPTION);
            }else{
            JOptionPane.showMessageDialog(null, "Select a row to delete","Medical Management System",
            JOptionPane.OK_OPTION);
                
            }
        }else{
            model.removeRow(jTable3.getSelectedRow());
        }
        
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.addRow(new Object[]{jComboBox3.getSelectedItem().toString(),
        jtxtReference.getText(),jtxtDose.getText(),jtxtNumberTablets.getText(),
        jtxtLOT.getText(),jtxtIssuedDate.getText(),jtxtExpDate.getText(),
        jtxtDailyDose.getText(),jtxtSideEffects.getText(),jtxtFurtherInformation.getText(),
        jtxtStorageAdvice.getText(),jtxtDriving.getText(),jtxtHowToUse.getText(),
        jtxtPatientID.getText(),jtxtDoctorNHSNo.getText(),
        jtxtPatientName.getText(),jtxtDateOfBirth.getText(),jtxtPatientAddress.getText()});
        
    }//GEN-LAST:event_jbUpdateActionPerformed

    private void jbDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDoctorActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medical_prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medical_prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medical_prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medical_prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medical_prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddress;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jDOB;
    private javax.swing.JLabel jDayDose;
    private javax.swing.JLabel jDose;
    private javax.swing.JLabel jDriving;
    private javax.swing.JLabel jExDate;
    private javax.swing.JLabel jFurthInfor;
    private javax.swing.JLabel jIssueData;
    private javax.swing.JLabel jLOT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNHSnum;
    private javax.swing.JLabel jNumTab;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jPatientID;
    private javax.swing.JLabel jPatientName;
    private javax.swing.JLabel jPrescription;
    private javax.swing.JLabel jReference;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jSideEffects;
    private javax.swing.JLabel jStorageAdvice;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jUse;
    private javax.swing.JButton jbAppointment;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbDoctor;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbLogin;
    private javax.swing.JLabel jbNameTablets;
    private javax.swing.JButton jbPatient;
    private javax.swing.JButton jbPerscription;
    private javax.swing.JButton jbPrint;
    private javax.swing.JButton jbReset;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDateOfBirth;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDriving;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowToUse;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLOT;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatientAddress;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextArea jtxtPrescription;
    private javax.swing.JTextField jtxtReference;
    private javax.swing.JTextField jtxtSideEffects;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
